### ISSUE TITLE
Library enhancement

### ISSUE THREAD

**Issue by proasnet** [paulino/ha-mqtt-entities#3] opened 2024-08-07 06:48 UTC
Dear @paulino
Do you think it would be possible to enhance your library with the following options?

- device manufacturer
- device model ( with possibility define value in setup() as a id and name )
- availability
- binary sensor

Your library is the best for my project and I miss these options.
Thank you so much

**Comment by paulino** [comment] 2024-08-12 21:19
I've uploaded a new `dev` branch with new features. I added new device attributes, the examples `examples/deviceproperties` and `examples/multiple` show two ways to set the attributes.

Binary sensor is easy to add. About availability, I'm not sure how it works, I'll read the HA docs

**Comment by proasnet** [comment] 2024-08-13 04:19
Dear @paulino ,
I can't find a new example in the last version you listed
`examples/deviceproperties` with new features.
Please check if the new example is shared on github.
Thank you very much.

**Comment by paulino** [comment] 2024-08-13 12:32
The changes are on the dev branch. I use dev branch for testing  before making a new release. Follow this link or select dev branch from the main project page:

[examples/deviceproperties](https://github.com/paulino/ha-mqtt-entities/tree/dev/examples/deviceproperties)

To test it, you need to clone the repo in the `Arduino/libraries` folder and switch to the dev branch

``` bash 
cd Arduino/libraries
git clone https://github.com/paulino/ha-mqtt-entities/
cd ha-mqtt-entities
git switch dev
```

**Comment by proasnet** [comment] 2024-08-14 05:38
Dear @paulino , I tried a dev branch library with use manufacturer, model and HW version and working fine.
Thank you very much.

**Comment by paulino** [comment] 2024-08-19 11:29
hi @proasnet

I've added some new functionality to the library:

- availability 
- binary sensor 
- some configuration features: device_class and icon

They can be tested in `dev` branch:

``` 
git switch dev 
git pull 
```

It is not fully tested, when works fine I'll release a new library version. They can be tested in the following way:

## Availability

Availability is implemented at the entity level and is not enabled by default. To use it, it must be set at setup time using the `addFeature` method:

```cpp

HASensor ha_sensor = HASensorBinary("my_sensor_id","Motion example");

void setup() {
    
    ...
    
    ha_sensor.addFeature(HA_FEATURE_AVAILABILITY);
    ha_sensor.setAvailable(false);

    ...

}
```

When entities are associated to a device, the availability can be set at the device level. But, this only works if the entities have the availability feature enabled. The `setAvailable` method  is also in the device class to enable or disable all entities associated with it. 

A full example is in [multipledevices.ino](https://github.com/paulino/ha-mqtt-entities/blob/dev/examples/multipledevices/multipledevices.ino) and [availability.ino](https://github.com/paulino/ha-mqtt-entities/blob/dev/examples/availability/availability.ino).


## Sensor features

They are extra keys/values supported by HA mqtt discovery.

All features need to be set at setup time using the method `addFeature`.  For example, to set switch icon or device class:

```cpp
HASensorBinary ha_sensor = HASensorBinary(SENSOR_ID,FRIENDLY_NAME);
HASensorBinary ha_motion_sensor = HASensorBinary(SENSOR_ID,FRIENDLY_NAME);

void setup() {
    ...
    
    ha_sensor.addFeature(HA_FEATURE_ICON,"mdi:lightbulb");
    ha_motion_sensor.addFeature(HA_FEATURE_DEVICE_CLASS,"motion");

    ...
}
```

Full example at  [sensorbinary.ino](https://github.com/paulino/ha-mqtt-entities/blob/dev/examples/sensorbinary/sensorbinary.ino) and [multipledevices.ino](https://github.com/paulino/ha-mqtt-entities/blob/dev/examples/multipledevices/multipledevices.ino).

**Comment by proasnet** [comment] 2024-08-20 05:04
Hi @paulino , I'm going to test the new features today. To begin with, it will be availability. I tried the availability.ino example and it works for the entity level. I am interested in availability for the entire device, i.e. if the esp32 is disconnected from the power supply, in HA the entire device will be as not available. How do I do this please?
I tried example multipledevices.ino with device availability. Example working if is esp powered.
After unplug a power from esp, device is still available a long time.
thank you

**Comment by proasnet** [comment] 2024-08-20 06:32
Dear @paulino 
Please allow me one more question.
I left the device on for a few days and during that time the connection to HA was lost. The status in HAMQTT.connected() was still true and recconect was not possible. Does your library have a function like HAMQTT.disconnect that allows this HAMQTT.connect() function to reconnect?

**Comment by paulino** [comment] 2024-08-21 09:12
> Dear @paulino Please allow me one more question. I left the device on for a few days and during that time the connection to HA was lost. The status in HAMQTT.connected() was still true and recconect was not possible. Does your library have a function like HAMQTT.disconnect that allows this HAMQTT.connect() function to reconnect?

I will remove the methods `connect` and `connected`. They are not needed because the connection can be managed with `Pubsubclient`.

With the current library version,  it is possible to work without these methods. I think is the better solution, for example, you can test this code:

```cpp

PubSubClient mqtt_client(wifi_client);

void setup()
{
   ...
    mqtt_client.setServer(MQTT_SERVER, MQTT_PORT);
    // Initialize entities and set mqttclient are mandatory
    HAMQTT.begin(mqtt_client, ENTITIES_COUNT);
    ...
}

void loop()
{
    if (WiFi.status() == WL_CONNECTED && !mqtt_client.connected())
    {
        if (mqtt_client.connect("examples", MQTT_USER, MQTT_PASSWORD))
            Serial.println("Connected to MQTT");
        else
        {
            Serial.println("Failed to connect to MQTT");
            delay(5000);
        }
    }
    HAMQTT.loop();
    delay(50);
}
```

**Comment by proasnet** [comment] 2024-08-21 09:35
Dear @paulino,
basically that's how I have it, and I'm having problems. I am sending you the cleaned code.
Connection is possible only one between wifi OR ethernet, never simultaneously.
```

WiFiClient wificlient;
EthernetClient ethernetclient;

PubSubClient wifi_mqtt_client( wificlient );
PubSubClient ethernet_mqtt_client( ethernetclient );
#define ENTITIES_COUNT 50

HADevice ha_device = HADevice( SW_VER );

void setup() {

  // some connections wifi or ethernet procedures...
  // wifi_connected and ethernet_connected are sets by status of wifi or ethernet


  if ( wifi_connected ) {
    wifi_mqtt_client.setServer( mqtt_adress.c_str() , MQTT_PORT );
    delay( 100 );
    HAMQTT.begin( wifi_mqtt_client, ENTITIES_COUNT );
  }
  if ( ethernet_connected ) {
    ethernet_mqtt_client.setServer( mqtt_adress.c_str() , MQTT_PORT );
    delay( 100 );
    HAMQTT.begin( ethernet_mqtt_client, ENTITIES_COUNT );
  }

  ha_device.setName( exchange_data.serial_number.c_str() );
  ha_device.setIdentifier( exchange_data.serial_number.c_str() );

  ...
}

void loop() {
  /*
    if ( millis() - mqtt_try_connection_interval >= 1000 && !HAMQTT.connected() && !HAMQTT.connect( exchange_data.serial_number.c_str() , EEPROM.readString( EEPROM_MQTT_USERNAME ).c_str() , EEPROM.readString( EEPROM_MQTT_PASSWORD ).c_str() )) {
    debug.println( "MQTT connecting..." );
    mqtt_connected = false;
    mqtt_try_connection_interval = millis();
    } else if ( !mqtt_connected ) {
    debug.println( "MQTT connected..." );
    mqtt_connected = true;
    mqtt_try_connection_interval = millis();
    }
  */

  mqtt_connected = HAMQTT.connected();

  if ( millis() - mqtt_try_connection_interval >= 1000 && !mqtt_connected ) {
    debug.println( F("MQTT connecting...") );
    if ( !HAMQTT.connect( exchange_data.serial_number.c_str() , EEPROM.readString( EEPROM_MQTT_USERNAME ).c_str() , EEPROM.readString( EEPROM_MQTT_PASSWORD ).c_str() ) ) debug.println( "Problem with MQTT connection..." );
    pb_mqtt = false;
    mqtt_connection_count++;
    mqtt_try_connection_interval = millis();
  }

  if ( mqtt_connected && !pb_mqtt ) {
    debug.println( F("MQTT connected...") );
    pb_mqtt = true;
    mqtt_connection_count = 0;
    EEPROM.write( EEPROM_MQTT_DISABLE_RST , false );
    EEPROM.writeByte( EEPROM_MQTT_RST_COUNT , 0 );
    EEPROM.commit();
    mqtt_try_connection_interval = millis();
  }

  if ( mqtt_connection_count >= 10 && !EEPROM.read( EEPROM_MQTT_DISABLE_RST )) {
    byte count = EEPROM.read( EEPROM_MQTT_RST_COUNT );
    count++;
    EEPROM.writeByte( EEPROM_MQTT_RST_COUNT , count );
    debug.println( "RST COUNTER: " + String( count ));
    EEPROM.commit();
    delay( 1000 );
    ESP.restart();
  }

  if ( EEPROM.readByte( EEPROM_MQTT_RST_COUNT ) >= 2 && !EEPROM.read( EEPROM_MQTT_DISABLE_RST ) ) {
    EEPROM.write( EEPROM_MQTT_DISABLE_RST , true );
    debug.println( F("MQTT connection auto restart disabled...") );
    EEPROM.commit();
  }



  HAMQTT.loop();
}
```

Please see 
https://github.com/paulino/ha-mqtt-entities/issues/4

**Comment by paulino** [comment] 2024-08-21 19:24
> Hi @paulino , I'm going to test the new features today. To begin with, it will be availability. I tried the availability.ino example and it works for the entity level. I am interested in availability for the entire device, i.e. if the esp32 is disconnected from the power supply, in HA the entire device will be as not available. How do I do this please? I tried example multipledevices.ino with device availability. Example working if is esp powered. After unplug a power from esp, device is still available a long time. thank you

Hi @proasnet

To disable entities when the connection is lost you need to use *Last will and testament (LWT)* from MQTT broker.

When a device is disconnected from the MQTT broker, the broker is the one to notify the clients that the device is offline. This library does not implement the LWT feature, because it relies on the *PubSubClient* library.

PubSubClient includes a feature called *Last Will and Testament* that must be set at connect time, see [pubsubclient connect method](https://pubsubclient.knolleary.net/api#connect)

This example show how to set entity disable after connection lost:

```cpp
void setup() {
    
    ...
    ha_switch.addFeature(HA_FEATURE_AVAILABILITY);
    // Initial states
    ha_switch.setState(true);
    ha_switch.setAvailable(true);
    ...

}

void loop()
{
    if (WiFi.status() == WL_CONNECTED && !mqtt_client.connected())
    {
        char will_topic[100];
        ha_switch.getAvailabilityTopic(will_topic);
        if (mqtt_client.connect("examples", MQTT_USER, MQTT_PASSWORD,
                will_topic,0,false,"offline"))
            Serial.println("Connected to MQTT");
        else
        {
            Serial.println("Failed to connect to MQTT");
            delay(5000);
        }
    }
    HAMQTT.loop();
    delay(50);
}
```

I think it works for a single entity, but if you want to disable all entities associated with a device it is more complex.

HA has a feature called `availability_mode` that can be set to all, any, and latest. I'm not sure how it works, I've never used it but you can try reading the [HA MQTT documentation](https://www.home-assistant.io/integrations/mqtt)

To disable all entities associated with a device entity, the `availability_mode` must be set to any of the valid entries `all`, `any`, and `latest`.

The problem is that LWT only sends offline messages to the topic of one entity, so you need to set the `availability_mode` to all in all entities associated with the device.

For example (not tested):

```cpp

void setup() {
    
    ...
    ha_switch.addFeature(HA_FEATURE_AVAILABILITY);
    ha_switch.addFeature("availability_mode","all");
    ha_sensor.addFeature(HA_FEATURE_AVAILABILITY);
    ha_sensor.addFeature("availability_mode","all");

        // Initial states
    ha_switch.setState(true);
    ha_switch.setAvailable(true);

    ...

}

void loop()
{
    if (WiFi.status() == WL_CONNECTED && !mqtt_client.connected())
    {
        char will_topic[100];
        ha_switch.getAvailabilityTopic(will_topic);
        if (mqtt_client.connect("examples", MQTT_USER, MQTT_PASSWORD,
                will_topic,0,false,"offline"))
            Serial.println("Connected to MQTT");
        else
        {
            Serial.println("Failed to connect to MQTT");
            delay(5000);
        }
    }
    HAMQTT.loop();
    delay(50);
    
}

```

**Comment by proasnet** [comment] 2024-08-22 06:55
Dear @paulino , I tested it in availability examle
```

/* ha-mqtt-entities library example of availability

  - Board: ESP32*

  This example shows the next:

  - Creates a text sensor with availability feature
  - Customize the icon of the test sensor
  - Create a switch to control the availability of the text sensor
  - Optimizes the memory usage by using PSTR to store the strings in flash memory

*/

#include <Arduino.h>
#include <WiFi.h>
#include <PubSubClient.h>
#include <HaMqttEntities.h>

// This file is not included in the repository only used for local testing
// #include "secrets.h"

// You must set the next defines
#ifndef SECRETS_H
#define WIFI_SSID "proasnet"
#define WIFI_PASSWORD "xxxxx"
#define MQTT_SERVER "xxxxxx"
#define MQTT_PORT 1883
#define MQTT_USER "xxxxxx"
#define MQTT_PASSWORD "xxxxx"
#endif

WiFiClient wifi_client;
PubSubClient mqtt_client(wifi_client);

// HA Parts
#define ENTITIES_COUNT 3
// This example optimizes the memory usage by using PSTR to store the strings
// in flash memory
#define SW_VERSION PSTR("1.0.0")
#define IDENTIFIER PSTR("example_availability")
#define DEVICE_NAME PSTR("Example of availability")

HADevice ha_device = HADevice(IDENTIFIER, DEVICE_NAME, SW_VERSION);
HAText ha_text = HAText(PSTR("text"), PSTR("Input text"), ha_device, 100);
HASwitch ha_switch = HASwitch(PSTR("switch"), PSTR("Test availability"), ha_device);

void ha_callback(HAEntity *entity, char *topic, byte *payload, unsigned int length);

void setup()
{
  Serial.begin(115200);
  mqtt_client.setServer(MQTT_SERVER, MQTT_PORT);

  // Initialize entities
  HAMQTT.begin(mqtt_client, ENTITIES_COUNT);
  HAMQTT.addEntity(ha_text);
  HAMQTT.addEntity(ha_switch);

  ha_text.addFeature(HA_FEATURE_AVAILABILITY);
  ha_text.addFeature("availability_mode", "all");
  ha_switch.addFeature(HA_FEATURE_AVAILABILITY);
  ha_switch.addFeature("availability_mode", "all");



  ha_text.addFeature(HA_FEATURE_ICON, "mdi:lightbulb");

  // Initial states
  ha_switch.setState(true);
  ha_text.setAvailable(true);
  ha_switch.setAvailable(true);
  ha_text.setState("Hello HomeAssistant");

  HAMQTT.setCallback(ha_callback);

  // start wifi
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
}

void loop()
{
  if (WiFi.status() == WL_CONNECTED && !mqtt_client.connected())
  {
    char will_topic[100];
    ha_text.getAvailabilityTopic(will_topic);
    ha_switch.getAvailabilityTopic(will_topic);
    
    if (mqtt_client.connect("examples", MQTT_USER, MQTT_PASSWORD,
                will_topic,0,false,"offline"))
      Serial.println("Connected to MQTT");
    else
    {
      Serial.println("Failed to connect to MQTT");
      delay(5000);
    }
  }
  HAMQTT.loop();
  delay(50);
}

/* Callback from HA-MQTT entities. It is called when an entity changes its state.

    Entity can be NULL when the received topic is not related to any entity.
    This is useful to handle other topics with the same mqtt client.
*/
void ha_callback(HAEntity *entity, char *topic, byte *payload, unsigned int length)
{
  if (entity == &ha_switch)
  {
    if (ha_switch.getState())
    {
      ha_text.setAvailable(true);
    }
    else
    {
      ha_text.setAvailable(false);
    }
  }
}
```

And esp cyclic restarting. Console:
```

ELF file SHA256: 86c0790b98630e92

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400d4e54  PS      : 0x00060c30  A0      : 0x800d4d4d  A1      : 0x3ffb2220  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x3f400147  A5      : 0x00000000  
A6      : 0x3ffb7c80  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3ffb2200  
A10     : 0x3ffb8c54  A11     : 0x00000200  A12     : 0x00000003  A13     : 0x00000001  
A14     : 0x00060a20  A15     : 0x00000001  SAR     : 0x00000019  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000008  LBEG    : 0x40089758  LEND    : 0x4008976e  LCOUNT  : 0x00000000  


Backtrace: 0x400d4e51:0x3ffb2220 0x400d4d4a:0x3ffb2240 0x400d283b:0x3ffb2260 0x400d5dc2:0x3ffb2290
```

**Comment by proasnet** [comment] 2024-08-22 07:27
The first example working, but only for one entity.

**Comment by paulino** [comment] 2024-08-22 19:05
I fixed the restart issue, it was here

``` cpp
ha_text.addFeature(HA_FEATURE_ICON, "mdi:lightbulb");
```

A new commit is in `dev` for this bug, please update dev branch and test again.

Anyway, I tested the code and only disable one entity, not all entities in the device. I think this is the HomeAssistant behavior. 

We will have to look for another solution online to disable all entities of the device when one entity is disabled ...

**Comment by paulino** [comment] 2024-08-23 19:26
> We will have to look for another solution online to disable all entities of the device when one entity is disabled ...

I've found a way to disable an entire device in the source code of the *Arduino Home Assistant integration* library.

It consists in sharing available topic in all entities of the device, so when the "offline" topic is sent from the broker, all entities are disabled at the same time.

I'll try implementing something similar but less complex next week.

**Comment by paulino** [comment] 2024-08-27 14:16
I upload a new commit at dev branch with an example of "Device availability". If you wish to test is at [deviceavailability.ino](https://github.com/paulino/ha-mqtt-entities/blob/824a335981572d87a9e318ad28c14557822316ff/examples/deviceavailability/deviceavailability.ino)

To simplify the code, the methods *HAMQTT.connect* and *HAMQTT.connected* are used for the *last-will* broker connection.

**Comment by proasnet** [comment] 2024-08-28 05:27
Dear @paulino ,
I tried the deviceavailability.ino example and it works as it should. Then I implemented it in the project and everything is fine as well. Thank you very much, your library is now working properly and it helped me a lot in my project. Great work.

**Comment by proasnet** [comment] 2024-08-28 06:40
I found one discrepancy, but I don't know what it is related to.
Device availability works, but some entities that had entity availability set to true are still available on an unavailable device. But it doesn't apply to everyone.

**Comment by proasnet** [comment] 2024-08-28 07:03
Dear @paulino 
I already found where it is related.
So, I have device availability set.
And for entities that have entity available set to true, they remain as online.
Is possible override it by device availability?
Thank you

**Comment by paulino** [comment] 2024-08-28 15:52
The MQTT specification only allows for one topic and payload to be set as last will topic.

When all entities share the same available topic, they are all enabled/disabled at the same time with the topic sent by the broker.

If one or more entities have a different available topic, they don't receive the last will topic.

I think there are two possible ways to get what you want:

1. One is to use an extra pubsubclient instance connected from the ESP32 with the last will topic of the entity which has it own available topic. This is not a good solution because you need multiple connections from ESP32 and it requires more resources. It is worse if multiple entities have available topic out of the device.

2. The other solution is to make an automation in HomeAssistant: when  one entity of the device goes offline publish an offline to the topic of all entities of the same device.

**Comment by proasnet** [comment] 2024-09-02 04:26
I used entity availability for entity availability by device type, some device types have less parameters. So I'll try another way. I will not use entity availability, and according to device type in setup() I will filter addEntity and the same in data update as setState.
So, on startup, unnecessary entities will not be created and updated.

**Comment by paulino** [comment] 2024-09-03 10:29
Ok It seems to be a valid solution, anyway HomeAssistant has a service to  trigger Mqtt topics from automations

I release a new library version with the all changes. Can you test if #4 is solved? Is for closing the issue if it is solved

**Comment by proasnet** [comment] 2024-09-04 06:53
Dear @paulino 
I tried the solution that I don't control the availability of the entities according to the device type, but I set the entities template by addEntity(), and the device availability already works as it should.
Thank you very much.

**Closed as completed** 2024-09-05 11:22 UTC
Labels: enhancement
